<?php

	/**
	 * Template für die Einstellungen des Bestellvariablen Moduls
	 */

?>
<script type="text/javascript">
/* <![CDATA[ */

    /**
     * Wird beim anlegen einer neuen Bestellvariable aufgerufen
     */
	function wpsg_addOV()
	{

		jQuery('#wpsg_ov_list').html('<img src="<?php echo WPSG_URL; ?>views/gfx/ajax-loader.gif" alt="<?php echo __('Bitte warten ...', 'wpsg'); ?>" />');
		
		jQuery.ajax( {
			url: '<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&action=module&modul=wpsg_mod_ordervars&noheader=1&do=add',
			success: function(data) {
				jQuery('#wpsg_ov_list').html(data);
			}
		} );
		
		return false;
		
	} // function wpsg_addOV()
            
/* ]]> */
</script>
<p><?php echo __('Wird eine Bestellvariable vom Type', 'wpsg') ?> <strong><?php echo __('"Auswahl"', 'wpsg') ?></strong> <?php echo __('angelegt, können die Optionen mit dem Pipe "|" Symbol getrennt angegeben werden.', 'wpsg') ?></p>
<p><strong><?php echo __('Bsp.:', 'wpsg')?></strong> <?php echo __('Auswahl_1 | Auswahl_2 | Auswahl_3', 'wpsg') ?></p>
<br />
<div class="wpsg_admin_box">		
		  		
	<div class="head">
		<div class="title">
			<div class="fulltab">
				<?php echo __('Bestellvariablen', 'wpsg'); ?>
				<a title="<?php echo __('Neue Bestellvariable anlegen', 'wpsg'); ?>" href="" class="wpsg_icon wpsg_icon_right wpsg_icon_add" onclick="return wpsg_addOV();"></a>
			</div>
		</div>
	</div>
	<div class="content" id="wpsg_ov_list">
		<?php echo $this->mod->ov_list(); ?>
	</div>
			
</div>