 <?php

	/**
	 * Render ein Variantenprodukt im Warenkorb (basket.phtml)
	 */

?>
<?php //wpsg_debug($this->view['variante']) ?> 
<tr class="wpsg_<?php echo (($this->view['i'] % 2 == 0)?'odd':'even'); ?>">
	<td><?php echo __('Variante', 'wpsg'); ?>:</td>
	<td colspan="<?php echo ((sizeof($this->view['basket']['mwst']) > 1 || $this->get_option('wpsg_showMwstAlways') == '1')?'3':'2'); ?>">
		<?php if (get_option('wpsg_vp_detailview') == 1) { ?>
		<?php foreach ($this->view['variante'] as $vari => $value) { ?>
		<?php if (is_numeric($vari)) { ?>
		<?php echo $value['name'] ?>: <?php echo $value['value'] ?>; <?php echo __('Art. Nr.', 'wpsg').': '.$value['artnr'] ?>; <?php echo $value['preis'] ?> <?php echo $this->get_option('wpsg_currency') ?>
		<br />
		<?php } ?>
		<?php } ?>							
		<?php } else { ?>
		<?php echo $this->view['variante']['key']; ?>
		<?php } ?>
	</td>
</tr>