<?php
	
	/**
	 * Mit diesem Template kann die Zeile eines Produktes im Mailtemplate erweitert werden
	 */

?>
<?php //wpsg_debug($this->view['variante']) ?>
<?php if (get_option('wpsg_vp_detailview') == 1) { ?>
<?php echo wpsg_pad_left($p['menge'], 5); ?><?php echo wpsg_translate(__('Variante:', 'wpsg'), "")."\n" ?>
<?php foreach ($this->view['variante'] as $vari => $value) { ?>
<?php if (is_numeric($vari)) { ?>
<?php echo wpsg_pad_left($p['menge'], 8); ?> <?php echo '- '.$value['name'] ?>: <?php echo $value['value'] ?>; <?php echo __('Art. Nr.', 'wpsg').': '.$value['artnr'] ?>; <?php echo $value['preis'] ?> <?php echo $this->get_option('wpsg_currency')."\n" ?>
<?php } ?>
<?php } ?>
<?php } else { ?>
<?php echo wpsg_pad_right(' ', 5); ?><?php echo __('Variante', 'wpsg'); ?>: <?php echo $this->view['variante']['key']; ?>
<?php } ?> 
