<?php

	/**
	 * Wird nach den Produkten in der Bestellzusammenfassung (overview) bei Variantenprodukten verwendet
	 */

?>
<tr class="wpsg_<?php echo (($this->view['i'] == 0)?'odd':'even'); ?>">
	<td><?php echo __('Variante', 'wpsg'); ?>:</td>
	<td colspan="<?php echo ((sizeof($this->view['basket']['mwst']) > 1 || $this->get_option('wpsg_showMwstAlways') == '1')?'2':'1'); ?>" class="wpsg_mod_varianten_value">
		<?php if (get_option('wpsg_vp_detailview') == 1) { ?>
		<?php foreach ($this->view['variante'] as $vari => $value) { ?>
		<?php if (is_numeric($vari)) { ?>
		<?php echo $value['name'] ?>: <?php echo $value['value'] ?>; <?php echo __('Art. Nr.', 'wpsg').': '.$value['artnr'] ?>; <?php echo $value['preis'] ?> <?php echo $this->get_option('wpsg_currency') ?>
		<br />
		<?php } ?>
		<?php } ?>							
		<?php } else { ?>
		<?php echo $this->view['variante']['key']; ?>
		<?php } ?>
	</td>
</tr>