<?php

	/**
	 * Dieses Template dient zur Integration der Admin Kontodaten in eine Bestellung (HTML)
	 */

?>
<p>
	<?php echo wpsg_translate(__('Bitte überweisen Sie den Rechnungsbetrag in Höhe von #1# auf folgendes Konto und geben Sie als Betreff <strong>#2#</strong> an.', 'wpsg'), wpsg_ff($this->view['basket']['sum']['preis_gesamt_brutto'], $this->get_option('wpsg_currency')), $this->view['mod_prepayment']['subject']); ?>
</p> 

<table style="width:100%;">
	<tr>
		<td><?php echo __('Kontoinhaber', 'wpsg'); ?>:</td>
		<td style="text-align:right;"><?php echo $this->replaceUniversalPlatzhalter($this->get_option('wpsg_mod_prepayment_kinhaber')); ?></td>
	</tr>
	<tr>
		<td><?php echo __('IBAN', 'wpsg'); ?>:</td>
		<td style="text-align:right;"><?php echo $this->replaceUniversalPlatzhalter($this->get_option('wpsg_mod_prepayment_iban')); ?></td>
	</tr>
	<tr>
		<td><?php echo __('Bank', 'wpsg'); ?>:</td>
		<td style="text-align:right;"><?php echo $this->replaceUniversalPlatzhalter($this->get_option('wpsg_mod_prepayment_bank')); ?></td>
	</tr>	
	<tr>
		<td><?php echo __('BIC-/SWIFT-Code', 'wpsg'); ?></td>
		<td style="text-align:right;"><?php echo $this->replaceUniversalPlatzhalter($this->get_option('wpsg_mod_prepayment_swift')); ?></td>
	</tr> 
 </table>