<?php

	/**
	 * Template für die Integration der Lieferzeit in den Warenkorb
	 */

?>
<tr class="wpsg_<?php echo (($this->view['i'] % 2 == 0)?'odd':'even'); ?>">	
	<td colspan="1"><?php echo __('Lieferzeit', 'wpsg'); ?>:</td>
	<td colspan="<?php echo ((sizeof($this->view['basket']['mwst']) > 1 || $this->get_option('wpsg_showMwstAlways') == '1')?'3':'2'); ?>" class="wpsg_cell_deliverytime_value" colspan="<?php echo ((sizeof($this->view['basket']['mwst']) > 1 || $this->get_option('wpsg_showMwstAlways') == '1')?'4':'3'); ?>">
		<?php echo $this->view['wpsg_mod_deliverytime']['deliverytime']; ?>
	</td>
</tr>