<?php

	/**
	 * Template für die Integration der Lieferzeit in die Bestellübersichtsseite
	 */

?>
<tr class="wpsg_<?php echo (($this->view['i'] % 2 == 0)?'odd':'even'); ?>">
	<td><?php echo __('Lieferzeit', 'wpsg'); ?>:</td>
	<td colspan="<?php echo ((sizeof($this->view['basket']['mwst']) > 1 || $this->get_option('wpsg_showMwstAlways') == '1')?'2':'1'); ?>" class="wpsg_cell_deliverytime_value">
		<?php echo $this->view['wpsg_mod_deliverytime']['deliverytime']; ?>
	</td>
</tr>
