<?php

	/**
	 * Template für die Eingabe der Lieferzeit im Produkt 
	 */

?> 
<?php if ($this->get_option('wpsg_mod_deliverytime_mode') == wpsg_mod_deliverytime::MODE_SELECT) { ?>
<?php echo wpsg_drawForm_Select('wpsg_mod_deliverytime[deliverytime]', __('Lieferzeit', 'wpsg'), $this->view['wpsg_mod_deliverytime']['arSelection'], $this->view['wpsg_mod_deliverytime']['deliverytime'], array('noIndex' => true)); ?>
<?php } else if ($this->get_option('wpsg_mod_deliverytime_mode') == wpsg_mod_deliverytime::MODE_DAYS) { ?>
<?php echo wpsg_drawForm_Input('wpsg_mod_deliverytime[deliverytime]', __('Lieferzeit', 'wpsg'), $this->view['wpsg_mod_deliverytime']['deliverytime'], array('unit' => __('Tage', 'wpsg'))); ?>
<?php } ?>