<?php

	/**
	 * Template für die Einstellungen des Lieferzeit Moduls
	 */

?>
<?php echo wpsg_drawForm_Select('wpsg_mod_deliverytime_mode', __('Eingabetyp', 'wpsg'), array(
	wpsg_mod_deliverytime::MODE_DAYS => __('Angabe von Tagen', 'wpsg'),
	wpsg_mod_deliverytime::MODE_SELECT => __('Auswahl', 'wpsg')		
), $this->get_option('wpsg_mod_deliverytime_mode'), array('help' => 'wpsg_mod_deliverytime_mode')); ?>
<div id="wpsg_mod_deliverytime_mode_<?php echo wpsg_mod_deliverytime::MODE_SELECT; ?>" class="wpsg_mod_deliverytime_mode">
	<?php echo wpsg_drawForm_Textarea('wpsg_mod_deliverytime_mode_select_values', __('Verfügbare Lieferzeiten', 'wpsg'), $this->get_option('wpsg_mod_deliverytime_mode_select_values'), array('help' => 'wpsg_mod_deliverytime_mode_select_values', 'hint' => __('Kommagetrennt', 'wpsg'))); ?>
	<?php echo wpsg_drawForm_Select('wpsg_mod_deliverytime_mode_select_default', __('Standard Lieferzeit', 'wpsg'), $this->view['wpsg_mod_deliverytime']['arSelection'], $this->get_option('wpsg_mod_deliverytime_mode_select_default'), array('help' => 'wpsg_mod_deliverytime_mode_select_default')); ?>
</div>
<div id="wpsg_mod_deliverytime_mode_<?php echo wpsg_mod_deliverytime::MODE_DAYS; ?>" class="wpsg_mod_deliverytime_mode">
	<?php echo wpsg_drawForm_Input('wpsg_mod_deliverytime_mode_days_default', __('Standard Lieferzeit', 'wpsg'), $this->get_option('wpsg_mod_deliverytime_mode_days_default'), array('help' => 'wpsg_mod_deliverytime_mode_days_default')); ?>
</div>

<br />

<?php echo wpsg_drawForm_Checkbox('wpsg_mod_deliverytime_show_product', __('Im Produkt anzeigen', 'wpsg'), $this->get_option('wpsg_mod_deliverytime_show_product'), array('help' => 'wpsg_mod_deliverytime_show_product')); ?>
<?php echo wpsg_drawForm_Checkbox('wpsg_mod_deliverytime_show_basket', __('Im Warenkorb anzeigen', 'wpsg'), $this->get_option('wpsg_mod_deliverytime_show_basket'), array('help' => 'wpsg_mod_deliverytime_show_basket')); ?>
<?php echo wpsg_drawForm_Checkbox('wpsg_mod_deliverytime_show_overview', __('In Bestellzusammenfassung anzeigen', 'wpsg'), $this->get_option('wpsg_mod_deliverytime_show_overview'), array('help' => 'wpsg_mod_deliverytime_show_overview')); ?>
<?php echo wpsg_drawForm_Checkbox('wpsg_mod_deliverytime_show_mail', __('In den Mails anzeigen', 'wpsg'), $this->get_option('wpsg_mod_deliverytime_show_mail'), array('help' => 'wpsg_mod_deliverytime_show_mail')); ?>

<script type="text/javascript">/* <![CDATA[ */

	jQuery(document).ready(function() {

		jQuery('#wpsg_mod_deliverytime_mode').bind('change', function() { 

			jQuery('.wpsg_mod_deliverytime_mode').hide();
			jQuery('#wpsg_mod_deliverytime_mode_' + jQuery(this).val()).show();
			
		} ).change();
		
	} );

/* ]]> */</script>
