<?php 

	/* Wichtig, da die Module sonst kein HTML zurückgeben */
	$this->htmlMail = true;

?>

<p><?php echo __('Hallo Administrator,', 'wpsg'); ?></p> 
 
<p><?php echo __('Eine neue Bestellung ist im Online-Shop eingegangen!', 'wpsg'); ?></p> 
 
<?php $this->render(WPSG_PATH_VIEW.'/mailtemplates/html/customer.phtml'); ?>

<br />

<h2><?php echo __('Warenkorb', 'wpsg'); ?> <a href="<?php echo WPSG_URL_WP.'wp-admin/admin.php?page=wpsg-Order&action=view&edit_id='.$this->view['o_id']; ?>"><?php echo __('Bestellverwaltung', 'wpsg'); ?></a>:</h2>

<?php $this->render(WPSG_PATH_VIEW.'/mailtemplates/html/order.phtml'); ?> 

<?php $this->callMods('mail_aftercalculation', array(&$this->view['basket']['checkout']['o_id'])); ?> 

<?php if (wpsg_isSizedString($this->view['basket']['checkout']['comment'])) { ?>
<h2><?php echo __('Bestellkommentar', 'wpsg') ?></h2>
<p><?php echo $this->view['basket']['checkout']['comment'] ?></p>
<?php } ?>