<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />        
        <title><?php echo $this->view['subject']; ?></title>
		<style type="text/css">
 
			#outlook a { padding:0; }  
			body { width:100% !important; } .ReadMsgBody{ width:100%; } .ExternalClass{ width:100%; }
			body { -webkit-text-size-adjust:none; } 
 
			body { margin:0; padding:0; padding-top:10px; line-height:115%; }
			img { border:0; height:auto; line-height:100%; outline:none; text-decoration:none; }
			table { border-collapse:collapse; }
			table th { background-color:#DDDDDD; vertical-align:middle; }
			table td, table th { padding:2px; line-height:100%; border-collapse:collapse; }
			table .td_bb { border-bottom:1px solid #000000; }
			table .td_bt { border-top:1px solid #000000; }
			#backgroundTable { margin:0; padding:0; width:100% !important; }

			body, #backgroundTable { line-height:150%; font-size:12px; background-color:#FAFAFA; font-family:sans-serif; }
			table td, table th { line-height:150%; font-size:12px; font-family:sans-serif; }
			h1 { font-size:1.2rem; }
			h2 { font-size:1.1rem; }
			h3 { font-size:1rem; }
			
			.contenttable { width:100%; border:0px; border-spacing:0px; }
			.contenttable th, .contenttable td { text-align:left; vertical-align:top; padding:0px; }
			.contenttable .col0 { width:50%; }
			.contenttable .col1 { width:50%; }
			
			.baskettable_wrap { } 
			.baskettable { border:1px solid #000000; width:100%; /*border-spacing:0px;*/ }
			.baskettable th, .baskettable td { text-align:left; }
			.baskettable .col_pos { width:40px; }
			.baskettable .col_price { width:100px; }
			.baskettable .col_amount { width:75px; text-align:center; }
			.baskettable .col_sum { text-align:right; width:100px; }
			
		</style>
	</head>
    <body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">
    	
    	<table id="backgroundTable">
    		<tr>
    			<td>&nbsp;</td>
    			<td style="width:600px; line-height:100%; vertical-align:middle;">    			