<?php

	/**
	 * Template für die Konfiguration der Topseller innerhalb der Produktverwaltung
	 */

?>
<?php if ($this->get_option('wpsg_mod_topseller_auto') == '1') { ?>
<?php echo wpsg_drawForm_Select('wpsg_mod_topseller[status]', __('TopSeller Status', 'wpsg'), array(
	'0' => __('Einbeziehen', 'wpsg'),
	'1' => __('Ausschließen', 'wpsg')
), $this->view['wpsg_mod_topseller']['status']); ?>
<?php } else { ?>
<?php echo wpsg_drawForm_Select('wpsg_mod_topseller[status]', __('TopSeller Status', 'wpsg'), array(
	'0' => __('Nicht anzeigen', 'wpsg'),
	'1' => __('Anzeigen', 'wpsg')
), $this->view['wpsg_mod_topseller']['status']); ?>		
<?php } ?>