<?php

	/**
	 * Template für die Anzeige des Produktgewichts im Warenkorb
	 */
	//wpsg_debug($this->view);
?>
<tr class="wpsg_<?php echo (($this->view['i'] % 2 == 0)?'odd':'even'); ?>">	
	<td colspan="1"><?php echo __('Gewicht', 'wpsg'); ?>:</td>
	<td class="wpsg_cell_weight_value" colspan="<?php echo ((sizeof($this->view['basket']['mwst']) > 1 || $this->get_option('wpsg_showMwstAlways') == '1')?'3':'2'); ?>">
		<?php echo wpsg_ff($this->view['weight'], $this->get_option('wpsg_mod_weight_unit')); ?>	
	</td>
</tr>