<?php
	
	/**
	 * Template für die Integration in die Verwaltung der Berechtigungen
	 */

	global $wpdb; $arRoles = get_option($wpdb->prefix."user_roles");

?>
<tr>
	<td class="wpsg_col_capname"><?php echo __('Kundenverwaltung', 'wpsg'); ?></td>
	<?php foreach ($arRoles as $role_key => $r) { ?>
	<td class="wpsg_col_cap">
		<input type="hidden" name="wpsg_cap[<?php echo $role_key; ?>][wpsg_customer]" value="0" />
		<input type="checkbox" <?php echo ((isset($r['capabilities']['wpsg_customer']) && $r['capabilities']['wpsg_customer'] == "1")?'checked="checked"':''); ?> name="wpsg_cap[<?php echo $role_key; ?>][wpsg_customer]" value="1" /> 
	</td>
	<?php } ?>
	<td></td>
</tr>	