<?php
	
	/*
	 * 
	 * Template für die Produktgruppenansicht im Frontend
	 * 
	 */ 

	// Produkte die neben dem Namen angezeigt werden sollen
	$showP = 4;
	
	if (!$this->hasMod("wpsg_mod_produktbilder")) die(__("Dieses Template erfordert das Modul mod_produktbilder.", "wpsg"));
	
	// Dimension der Bilder
	$picW = 150;
	$picH = 100;	
	$picMode = 's';

?>
<?php //wpsg_debug($this->view['data']) ?>
<?php $c = 0; foreach ((array)$this->view['data'] as $k => $g) { ?>
<?php //wpsg_debug($g) ?>
<div class="wpsg_pgruppen_list_row">
	<div class="wpsg_pgruppen_list_titel">
		<a href="<?php echo WPSG_URL_WP ?>?page_id=<?php echo get_the_ID(); ?>&show=<?php echo $k ?>">
			<?php echo $g['pgruppe_name'] ?>
		</a>
	</div>
	<div class="wpsg_pgruppen_list_produkte">	
		<?php for ($i = 0; $i < $showP && $i < sizeof($g['produkte']); $i ++) { ?>
			<?php $image = array_rand($g['produkte'][$i]['bilder']); ?>
			<?php if ($image >= 0 && is_int($image)) { ?>
			<div class="wpsg_pgruppen_list_image">
				<?php $image_path = $this->callMod('wpsg_mod_produktbilder', 'makeTn', array($g['produkte'][$i]['id'], $g['produkte'][$i]['bilder'][$image], $picW, $picH, $picMode)) ?>
				<a href="<?php echo $g['produkte'][$i]['url'] ?>">
					<img src="<?php echo $image_path; ?>" alt="<?php echo $g['produkte'][$i]['name']; ?>"/>
				</a>
			</div>
			<?php } ?>
		<?php } ?>
		<div style="clear:both;"></div>			
	</div>
</div>
<?php $c++ ?>
<?php } ?>