<?php

	/**
	 * Template für eine Produktzeile bei der Bestellzusammenfassung
	 */

?>
<?php if (is_array($this->view['wpsg_mod_productvars']['data']) && sizeof($this->view['wpsg_mod_productvars']['data']) > 0) { ?>
<?php foreach ($this->view['wpsg_mod_productvars']['data'] as $pv) { ?>
<tr class="wpsg_<?php echo (($this->view['wpsg_mod_productvars']['i'] == 0)?'odd':'even'); ?>">
	<td><?php echo __($pv['name'], 'wpsg'); ?>:</td>
	<td class="wpsg_cell_gesamtpreis" colspan="<?php echo ((sizeof($this->view['basket']['mwst']) > 1 || $this->get_option('wpsg_showMwstAlways') == '1')?'2':'1'); ?>">
		<?php if ($pv['typ'] == '1') { // Auswahl ?>
			<?php if ($this->view['wpsg_mod_productvars']['p']['wpsg_mod_productvars'][$pv['id']] == 'not_set') { ?>
			<?php echo __('Nicht angegeben', 'wpsg'); ?>
			<?php } else { ?>
			<?php echo wpsg_hspc($this->view['wpsg_mod_productvars']['p']['wpsg_mod_productvars'][$pv['id']]); ?>
			<?php } ?>
		<?php } else if ($pv['typ'] == '2') { // Textfeld ?>
			<?php echo wpsg_hspc($this->view['wpsg_mod_productvars']['p']['wpsg_mod_productvars'][$pv['id']]); ?>
		<?php } else if ($pv['typ'] == '3') { // Checkbox ?>
			<?php if ($this->view['wpsg_mod_productvars']['p']['wpsg_mod_productvars'][$pv['id']] == '1') { ?>
			<?php echo __('Ja', 'wpsg'); ?>
			<?php } else { ?>
			<?php echo __('Nein', 'wpsg'); ?>
			<?php } ?>
		<?php } ?>
	</td>
</tr>
<?php } ?>
<?php } ?>