<?php

	/*
	 * Aktivierung der Produktvariablen in der Produktvarwaltung
	 */

?>
<div id="wpsg_productvars" class="postbox">
	<h3 class="wpsg_handlediv">
		<span title="<?php echo __('Zum Ein/Ausklappen hier klicken', 'wpsg'); ?>" class="handlediv"><br /></span>
		<span><?php echo __('Produktvariablen', 'wpsg'); ?> </span>
	</h3>
	<div class="inside">
		<?php if (is_array($this->view['wpsg_mod_productvars']['data']) && sizeof($this->view['wpsg_mod_productvars']['data']) > 0) { ?>		
			<?php foreach ($this->view['wpsg_mod_productvars']['data'] as $pv) { ?>
			<?php echo wpsg_drawForm_Checkbox('wpsg_pv['.$pv['id'].']', __($pv['name'], 'wpsg'), ((in_array($pv['id'], (array)$this->view['wpsg_mod_productvars']['productvars_set']))?true:false)); ?>
			<?php } ?>
		<?php } else { ?>
		 	<?php echo __('Bisher keine Produktvariablen angelegt.', 'wpsg'); ?>
		<?php } ?>
		<br />
		<a href="<?php echo WPSG_URL_WP; ?>wp-admin/admin.php?page=wpsg-Admin&amp;action=module&amp;modul=wpsg_mod_productvars"><?php echo __('Zur Produktvariablenverwaltung', 'wpsg'); ?></a>
	</div>
</div>
