<?php

	/**
	 * Template für die Rabattkonfiguration innerhalb der Produktverwaltung
	 */

?>
<div id="wpsg_discount" class="postbox">
	<h3 class="wpsg_handlediv">
		<span class="handlediv" title="<?php echo __('Zum Ein/Ausklappen hier klicken', 'wpsg'); ?>"><br /></span>
		<span><?php echo __('Produktrabatt', 'wpsg'); ?> </span>
	</h3>
	<div class="inside">	
		<?php echo wpsg_drawForm_Checkbox('wpsg_mod_discount[discount_aktiv]', __('Aktion aktiv', 'wpsg'), $this->view['wpsg_mod_discount']['data'][0]); ?>
		<?php echo wpsg_drawForm_Input('wpsg_mod_discount[discount_from]', __('Start (TT.MM.JJJJ)', 'wpsg'), wpsg_hspc($this->view['wpsg_mod_discount']['data'][1])); ?>
		<?php echo wpsg_drawForm_Input('wpsg_mod_discount[discount_to]', __('Ende (TT.MM.JJJJ)', 'wpsg'), wpsg_hspc($this->view['wpsg_mod_discount']['data'][2])); ?>
		<?php echo wpsg_drawForm_Input('wpsg_mod_discount[discount_value]', __('Rabatt', 'wpsg'), wpsg_ff($this->view['wpsg_mod_discount']['data'][3])); ?>
	</div>
</div>