<?php

	/**
	 * Template für die Integration des Bewertungslinkes in die Kundenmail
	 */


?><?php echo $this->get_option('wpsg_mod_trustedshops_customermailtitle'); ?> 
https://www.trustedshops.de/bewertung/bewerten_<?php echo $this->get_option('wpsg_mod_trustedshops_shopid'); ?>.html&buyerEmail=<?php echo urlencode(base64_encode($this->view['customer']['email'])); ?>&shopOrderID=<?php echo urlencode(base64_encode($this->view['order']['onr'])); ?>
 