<?php

	/**
	 * Template für die Ausgabe des Trusted Shops Widgets im Frontend
	 */

?>

<?php if ($this->view['settings']['wpsg_mod_trustedshops_siegel'] == '1') { ?>
<div class="wpsg_mod_trustedshops_siegel">
	
</div>
<?php } ?>

<?php if ($this->view['settings']['wpsg_mod_trustedshops_vote'] == '1') { ?>
<div class="wpsg_mod_trustedshops_vote">
	<a target="_blank" href="https://www.trustedshops.de/bewertung/info_<?php echo $this->get_option('wpsg_mod_trustedshops_shopid'); ?>.html" title="<?php echo wpsg_hspc($this->get_option('wpsg_mod_trustedshops_siegeltitle')); ?>">
		<img class="bewertung" alt="<?php echo wpsg_hspc($this->get_option('wpsg_mod_trustedshops_siegeltitle')); ?>" border="0" src="<?php echo $this->view['siegelURL']; ?>"/>
	</a>
</div>
<?php } ?>

<?php if ($this->view['settings']['wpsg_mod_trustedshops_badge'] == '1') { ?>
<script type="text/javascript">/* <![CDATA[ */
	
    (function () { 
    var _tsid = '<?php echo $this->get_option('wpsg_mod_trustedshops_shopid'); ?>'; 
    _tsConfig = { 
    	      'yOffset': '0', /* offset from page bottom */
    	      'variant': 'reviews', /* text, default, small, reviews, custom, custom_reviews */
    	      'customElementId': '', /* required for variants custom and custom_reviews */
    	      'trustcardDirection': '', /* for custom variants: topRight, topLeft, bottomRight, bottomLeft */
    	      'customBadgeWidth': '', /* for custom variants: 40 - 90 (in pixels) */
    	      'customBadgeHeight': '', /* for custom variants: 40 - 90 (in pixels) */
    	      'disableResponsive': 'false', /* deactivate responsive behaviour */
    	      'disableTrustbadge': 'false', /* deactivate trustbadge */
    	      'trustCardTrigger': 'mouseenter' /* set to 'click' if you want the trustcard to be opened on click instead */
    };
    var _ts = document.createElement('script');
    _ts.type = 'text/javascript'; 
    _ts.charset = 'utf-8'; 
    _ts.async = true; 
    _ts.src = '//widgets.trustedshops.com/js/' + _tsid + '.js'; 
    var __ts = document.getElementsByTagName('script')[0];
    __ts.parentNode.insertBefore(_ts, __ts);
    })();
    
/* ]]> */</script>
<noscript><a href="https://www.trustedshops.de/shop/certificate.php?shop_id=<?php echo $this->get_option('wpsg_mod_trustedshops_shopid'); ?>"><img title="<?php echo __('Klicken Sie auf das Gütesiegel, um die Gültigkeit zu prüfen!', 'wpsg'); ?>" src="//widgets.trustedshops.com/images/badge.png" style="position:fixed;bottom:0;right:0;" /></a></noscript>
 <?php } ?>

